title: "Liam Noone — A* Pathfinding"
description: "A* algorithm implementation in C++ with interactive visualizer"
url: "https://liamnooneatu.github.io"
baseurl: "/A-Star-Algorithm"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "neon"   # options: default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
